{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pandas'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[14], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mrequests\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mpd\u001b[39;00m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mio\u001b[39;00m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'pandas'"
     ]
    }
   ],
   "source": [
    "\n",
    "import requests\n",
    "import pandas as pd\n",
    "import io\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in c:\\users\\sasi\\appdata\\local\\programs\\python\\python312\\lib\\site-packages (2.2.2)\n",
      "Requirement already satisfied: numpy>=1.26.0 in c:\\users\\sasi\\appdata\\local\\programs\\python\\python312\\lib\\site-packages (from pandas) (1.26.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\sasi\\appdata\\roaming\\python\\python312\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\sasi\\appdata\\local\\programs\\python\\python312\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\sasi\\appdata\\local\\programs\\python\\python312\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\sasi\\appdata\\roaming\\python\\python312\\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pandas\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "headers = {\n",
    "    'Accept':'*/*',\n",
    "    'Accept-Encoding':'gzip, deflate, br, zstd',\n",
    "    'Accept-Language':'en-GB,en-US;q=0.9,en;q=0.8',\n",
    "    'Cookie':'defaultLang=en; nseQuoteSymbols=[{\"symbol\":\"INFY\",\"identifier\":null,\"type\":\"equity\"}]; ak_bmsc=0389ECC4CD7BC11774769591D36F0674~000000000000000000000000000000~YAAQBdksMSun5qSPAQAAE6MtvhdGHhaHK1NdxtAqmSH6VUaXM7VYzOMramUZEuT9a/4PKoX4bacxSOCj4YHJZ63jRIZQrXznwmT4guaimpbJHQwWUJNQJzES3c6K5O+BDe0JRbVxE62cUIu1Eao8FWKJJqFqoTFaskQPfTnDx9W712++HAsk3R0D5gVC9P5EV3nR23bPkmL00Unr5weB0NsD4u1TXUwRUeAXxKS2d++yqBn+RdsfezwLzqIqdAFUj9Pm+VdSbY/KihPxOJIGmbV/WlxA/q48wbtWQdR3fow7jNkl5ch91uQ79hdGpaUZAwVAMugmKNkwb3yBaZoTPVbymRsolHx17rDkIzsBXiWuUdYwWh8/6PB8dYwNFXXAlCrTFMk0s7DfrkNn; nsit=1HsaXeTJz0vMIwteUphLxkq1; nseappid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkubnNlIiwiYXVkIjoiYXBpLm5zZSIsImlhdCI6MTcxNjg4MzM0MywiZXhwIjoxNzE2ODkwNTQzfQ.-d_LhHghe2UPA05KnDwKfMe2VnwjPFQPniqbadWAPjU; AKA_A2=A; bm_mi=9F134401ECE4D0098A177C7B9B236141~YAAQ5cYsMUIS8LmPAQAALMk4vhfVbX/1Vl9Mehkh25Y624q2cpC1EIA0xTBuanD8uifaHvaND+sUKQRohxflZkdUVh8LjAvOsWtITwCKSaFj3er9MEzhdwqAr6ZH6pe+o7q3AkDEo/j/UuDoQvgXunMtASnMBtN9dy2oqXXeF/LvMm3Pjnv5EoM7SrdbPw4R20EpOOfBLCRQUOmaVepvJxMuM/Dat99fKPnhq5E+l374Z/Ir5q0hQGMi0qs8jivfN1jyhNjX4mOjxGmqA9zfD/Qid/qhGEDVvA/p6d7r/JXTMdOhWezEMMdrIK79ogdUwFy14dQomQADi+/Jh1V9oS0=~1; bm_sz=136D70B4F6D891EC3722216B7CF342DC~YAAQ5cYsMUQS8LmPAQAALMk4vheWjNb8+llrV1/e9y6KVORIDxI2RAOmEqm2ZW4+IHg3LrdeAXguHpicBbGOf83GWtgR8zNCBPELlQf/3+LHz8C8t/1230/eSwxN0jMJ80SANBqakKKwcHMfN/YPCEiw4h/OfL6HxQNo3Fm5u8ebBnGeMb/CkecTT5M+D3rp9MLhMPq83uML9knePnWklhbcwemLfdyUajgPHPwT5fMv/qmQrMZwKJegqljKcD6Y01QHJdybderNkgKTzHkZ7JIfbuFd1/MXxCl2xFgGHw2YsK7Wu+PVIPmBaIc+VTPkZn6eCaiVoU9S9BaOpQuTM0NXQmIQ/dlNRH+GpJ4AwiThf+gGk7FX8QQxz+wVDiodwPHqzLRZvUX/T7frDcESbereayRUdCpT/KHRavS2ePTRUtwAbfNGtmXB2ZSaE4BhV4EkhS6X0UZ1BJuju8u9BSHm~4601398~3360307; _abck=F863A17082100C5FD95FA7AF10363755~0~YAAQ5cYsMekU8LmPAQAAziE5vguxEv2TaJ7bPEPwljpo/yi9c9KOG4iad3Mui2Bqmu6Bv+uYOwQIRH5YIFU+BJtIkRp82pOSkJnKgg5X3apam7N36qLhx+vJ59R94y0/K2ue4k8cRRIDycdbX0nWarWsMdT4w7OW2KXAKk4xfyeOUY40VOXFUm1Be2SlM8xw6uymUED6D/OIJVgaLq/kwmtwaQVfYobUCfCcjUTQnq3eJVgW02T6CAfbvDQKk9E49+9IxxX4hXa1CkndSOHRHa1VApuapCCR52fZmR4SMgdBnmyaPboIQIni/KNOaQYAEofAXQKfin6BroYvjHBhrUIyKEXtJiIzjRleRFUoGoLlpNiR+or1uu6y6u0wAxaU~-1~-1~-1; bm_sv=A8BB97C4356F155205AD8CE9DFEF5408~YAAQ5cYsMeoU8LmPAQAAziE5vhcU3Xxs+53p4locpZrOi3Hvt1Jvb11VlUwkhmYefeLqj22Ci8w+ScXLp/VYsYnaRjlL3KaGHUwMUmZC1Mh/08D81ckiP2iMwQEyRIeNEwrKh7x0tgmcMRBrTbyfBC5imIetauE2qzqBt/edWT4p5zPJtVZzopQT2zom8LSnx4pDJb9EuqScw8eSPD0+Xu+7ltZvUtaKIqXvyidMSXxuB4/mrq2SJOyfyGGLlkTKMfqP~1',\n",
    "    'Priority':'u=1, i',\n",
    "    'Referer':'https://www.nseindia.com/get-quotes/equity?symbol=INFY',\n",
    "    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "response = requests.get(url = 'https://www.nseindia.com/api/historical/cm/equity?symbol=INFY&series=[%22EQ%22]&from=28-05-2023&to=28-05-2024',headers=headers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Response [200]>"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'pd' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[13], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m response\u001b[38;5;241m.\u001b[39mcontent\n\u001b[1;32m----> 2\u001b[0m infosys_data \u001b[38;5;241m=\u001b[39m \u001b[43mpd\u001b[49m\u001b[38;5;241m.\u001b[39mread_csv(io\u001b[38;5;241m.\u001b[39mStringIO(response\u001b[38;5;241m.\u001b[39mcontent\u001b[38;5;241m.\u001b[39mdecode(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mutf-8\u001b[39m\u001b[38;5;124m'\u001b[39m)))\n",
      "\u001b[1;31mNameError\u001b[0m: name 'pd' is not defined"
     ]
    }
   ],
   "source": [
    "response.content\n",
    "infosys_data = pd.read_csv(io.StringIO(response.content.decode('utf-8')))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
